### ISSUE TITLE
Add game endings

### ISSUE THREAD

**Issue by kenshinthebattosai** [kenshinthebattosai/CAESAR#47]
From [Journal Entry 09](blob/master/docs/09%20-%20The%20Rules%20of%20Chess.md)

- [x] Add Check
- [x] Add Checkmate
- [x] Add Draw
  - [x] By #46 50 move rule
  - [x] By #48 3-fold repetition
  - [x] By #59 stalemate
  - [x] ~~By accepting a draw offer~~ (will revisit later)
  - [x] By #63 insufficient material
- [x] Add Outcomes to Game, along with Reasons and Rules
